steps:
- name: "gcr.io/cloud-builders/gcloud"
  env:
    - 'DB_HOST=${_DB_HOST}'
    - 'DB_USER=${_DB_USER}'
    - 'DB_PASS=${_DB_PASS}'
    - 'DB_NAME=${_DB_NAME}'
    - 'DB_PORT=${_DB_PORT}'
  args: ["app", "deploy"]
timeout: "1600s"